### ISSUE TITLE
Erreur "unknown time zone Europe/Paris"

### ISSUE THREAD

**Issue by DegrangeM** [hekmon/edfbleu#12]
Lors de l'exécution de la commande, j'obtiens l'erreur "unknown time zone Europe/Paris" (Windows 10, version EDF Bleu 20230809).
Merci.

**Comment by hekmon** [comment]
Le programme ne contient pas les timezones lui même mais les charge depuis l'OS. Votre Windows 10 a-t-il un pack de langue Français installé ?

De mon côté j'essayerai d'intégrer les timezones directement dans le programme pour la prochaine version, j'ai une [piste](https://pkg.go.dev/time/tzdata@go1.21.0).

**Comment by DegrangeM** [comment]
Oui mon windows est bien configuré en Français (et l'heure est bien configuré sur le fuseau horaire de paris).

**Comment by DegrangeM** [comment]
(après ce n'est pas urgent, je suis passé sous linux pour avoir mon estimation)

**Comment by hekmon** [comment]
Disponible dans la version [20231030](https://github.com/hekmon/edfbleu/releases/tag/20231030) !
