### ISSUE TITLE
Windows : Ajouter .exe au nom de l'exécutable

### ISSUE THREAD

**Issue by DegrangeM** [hekmon/edfbleu#13]
Actuellement, le fichier windows ne se termine pas par .exe et il faut donc d'abord renommer le fichier afin de pouvoir exécuter la ligne de commande.

**Comment by hekmon** [comment]
C'est... vrai !

Ça sera le cas pour la prochaine version (après mes congés ;).

**Comment by hekmon** [comment]
Disponible dans la version [20231030](https://github.com/hekmon/edfbleu/releases/tag/20231030) !
