### ISSUE TITLE
Mise a jour des jours tempo

### ISSUE THREAD

**Issue by alex3979** [hekmon/edfbleu#14]
Bonjour, 

Un grand merci pour le travail réaliser, c'est top !

Serais t-il possible d'avoir une mise a jour des jours tempo ?

Remarque au passage, il y a un oubli pour le "12/06/2023" qui est blanc 

Merci d'avance

**Comment by hekmon** [comment]
Il n'y a pas eu de jours blanc ou rouge depuis la dernière mise à jour du programme donc le résultat devrait déjà être bon (hormis l'oubli du 12/06/2023, merci pour votre vigilance) malgré le message d'avertissement !

**Comment by hekmon** [comment]
Disponible dans la version [20231030](https://github.com/hekmon/edfbleu/releases/tag/20231030) !

**Comment by alex3979** [comment]
Merci !
