### ISSUE TITLE
out of range?

### ISSUE THREAD

**Issue by moreje** [hekmon/edfbleu#16]
Hello,
je viens de tester  le simulateur et j'ai ce retour:
/!\ the data set contains values that are beyong the internal data this program has. Please update the code.

faut il attendre une mise à jour?

**Comment by hekmon** [comment]
Absolument, je m'en occupe dès que possible.

En attendant vous pouvez utiliser des exports Enedis qui ne dépassent pas la [date de dernière mise à jour](https://github.com/hekmon/edfbleu/blob/main/bleu.go#L9).

**Comment by hekmon** [comment]
Corrigé par @alexandredubois dans la MR #18 (une nouvelle release arrive sous peu avec les correctifs).

**Comment by hekmon** [comment]
Disponible dans la [dernière version](https://github.com/hekmon/edfbleu/releases/tag/20240112).
