### ISSUE TITLE
failed to parse header: invalid headers, expecting 9 got 8

### ISSUE THREAD

**Issue by alexandredubois** [hekmon/edfbleu#17]
[Enedis_Conso_Jour_20231130-20240110_16105064920409.csv](https://github.com/hekmon/edfbleu/files/13903913/Enedis_Conso_Jour_20231130-20240110_16105064920409.csv)

Bonjour,
Après avoir téléchargé le fichier Enedis en PJ et exécuté le binaire inclus dans edfbleu_20231030_windows_amd64.zip avec la ligne de commande `edfbleu.exe -csv ./Enedis_Conso_Jour_20231130-20240110_16105064920409.csv` j'obtiens l'erreur suivante : 

`2024/01/11 14:38:09 failed to parse header: invalid headers, expecting 9 got 8: ﻿Identifiant PRM, Type de donnees, Date de debut, Date de fin, Grandeur physique, Grandeur metier, Etape metier, Unite`

**Comment by hekmon** [comment]
Je me demande si ce n'est pas lié à #15 . Les deux semblent indiquer un changement de format de la part d'Enedis.

Je regarde dès que possible.

**Comment by alexandredubois** [comment]
Super, merci d'avance

**Comment by alexandredubois** [comment]
Merci pour votre retour :)
Pour information, je n'avais pas cette option de disponible dans mon compte client ENEDIS, j'ai creusé et découvert qu'il fallait activer cette collecte horaire pour que les données soient accessibles. Malheureusement je ne pense pas que ce soit rétroactif, ce qui va limiter l'usage de mon côté !

Si d'autres se retrouve dans la même situation, cette option de collecte s'active ici : https://mon-compte-particulier.enedis.fr/donnees

**Comment by hekmon** [comment]
Merci pour eux 👍
