### ISSUE TITLE
Trojan edfbleu_20240201_windows_amd64.zip

### ISSUE THREAD

**Issue by kefrens** [hekmon/edfbleu#20]
Hello,
J'essaie de telecharger la release Trojan edfbleu_20240201_windows_amd64.zip mais Windows Defender trouve un 
Trojan:Win32/Wacatac.B!ml

Pouvez-vous confirmer?
Merci

**Comment by hekmon** [comment]
Étrange...

Je n'ai pas de windows defender donc je ne peux pas vous dire. Tout ce que je peux vous donner c'est un rapport multi antivirus directement sur le fichier en téléchargement depuis github: [VirusTotal](https://www.virustotal.com/gui/url/10c3171d54e5a400c54afb68c85b5daf3871e04b71289c05a336dd9d463f07b2) (0/91).

Si vous avez un doute, n'hésitez pas a recompiler le programme vous même :

- Installer [Go](https://go.dev/doc/install)
- Lancer la compilation depuis le repo avec `go build -ldflags="-s -w" -o "edfbleu.exe" -tags timetzdata`

**Comment by hekmon** [comment]
Sans retour de votre part, je me permet de fermer l'issue (mais vous pouvez toujours y répondre).
