### ISSUE TITLE
Configure HC ranges for tarif plan HPHC

### ISSUE THREAD

**Issue by jaypif** [hekmon/edfbleu#6]
HC depends on area where consumer lives. 
For the moment the ranges starting from 22h30 to 7h30 in the morning is not correct.

Usually HC tarif plan is split in 2 ranges: 6h during the night between 22h30 and 7h30 and 2h between 12h and 16h. 
The real ranges are set by ENEDIS.

So it could be nice to support 2 ranges for HC in the CLI call.

**Comment by hekmon** [comment]
#5 merged, thanks !
